[package]
org = "shammi"
name = "cipher_tool"
version = "0.1.0"
distribution = "2201.13.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "toml"
version = "0.8.0"
